/* global React */
// Bilingual strings — fr is the Figma source language, en is the polished translation.

const I18N = {
  fr: {
    // chrome
    project: "Projet 1",
    brand: "IBEE",
    weather: "21°",
    weatherDesc: "Ensoleillé · Lyon",
    // sidebar
    general: "Générale",
    home: "Accueil",
    analytics: "Analyse",
    marketing: "Marketing",
    revenue: "Revenu",
    payment: "Paiement",
    drive: "Drive",
    portfolio: "Portfolio",
    tools: "Outils",
    automation: "Automation",
    connector: "Connecteur",
    settings: "Mon compte",
    account: "Compte",
    privacy: "Confidentialité",
    notifications: "Notification",
    team: "Équipe",
    activity: "Activité",
    research: "Recherche",
    messages: "Messages",
    // profile
    profileSection: "Section du profil",
    follow: "Suivre",
    subscribe: "S'abonner",
    share: "Partager",
    editMode: "Mode édition",
    follower: "abonnés",
    sendMessage: "Envoyer un message",
    professional: "Professionnel",
    manager: "Manager",
    active: "Actif",
    inactive: "Inactif",
    // tabs (locked to English across languages: shop, event, news)
    info: "Info",
    home: "Accueil",
    homeTab: "Home",
    profileWebTab: "Profile web",
    shop: "Shop",
    event: "Event",
    service: "Service",
    news: "News",
    video: "Vidéo",
    bio: "Bio",
    faq: "F.A.Q",
    parcours: "Parcours",
    histoire: "Histoire",
    // header menu
    headerProfile: "Profile",
    headerSwitchLang: "English",
    darkMode: "Mode sombre",
    lightMode: "Mode clair",
    logout: "Déconnexion",
    customLinks: "Liens",
    reportAccount: "Signaler le compte",
    blockAccount: "Bloquer",
    copyLink: "Copier le lien",
    // bio
    aboutMe: "À propos",
    contact: "Contact",
    stats: "Statistiques",
    yearsActive: "Années d'activité",
    projects: "Projets réalisés",
    clients: "Clients",
    location: "Localisation",
    // service
    all: "Tout",
    package: "Forfait",
    haircut: "Coupe & coiffure",
    beard: "Service barbe",
    smoothing: "Lissage",
    // research
    discover: "Découvrez les talents",
    discoverSub: "Centralisez tout ce qu'un site peut faire — dans un seul profil.",
    searchPlaceholder: "Cherchez un coiffeur, photographe, coach...",
    searchBtn: "Rechercher",
    trending: "Tendances",
    nearby: "Près de chez vous",
    // empty
    nothingHere: "Rien à voir pour le moment",
    addContent: "Ajoutez du contenu en mode édition.",
    // revenu
    thisMonth: "Ce mois-ci",
    lastMonth: "Mois dernier",
    paid: "Encaissé",
    pending: "En attente",
    // paiement
    addCard: "Ajouter une carte",
    defaultCard: "Par défaut",
    expires: "Expire",
    // automation
    addStep: "Ajouter une étape",
    // generic
    save: "Enregistrer",
    cancel: "Annuler",
    close: "Fermer",
    activate: "Activer",
    deactivate: "Désactiver",
    drag: "Glisser pour réorganiser",
    open: "Ouvert",
    closed: "Fermé",
    fileName: "Nom",
    fileSize: "Taille",
    fileModified: "Modifié",
    fileOwner: "Propriétaire",
    upload: "Téléverser",
    newFolder: "Nouveau dossier",
    me: "Moi",
    you: "Vous",
    today: "Aujourd'hui",
    yesterday: "Hier",
    typeMessage: "Écrire un message...",
    send: "Envoyer",
  },
  en: {
    project: "Project 1",
    brand: "IBEE",
    weather: "21°",
    weatherDesc: "Sunny · Lyon",
    general: "General",
    home: "Home",
    analytics: "Analytics",
    marketing: "Marketing",
    revenue: "Revenue",
    payment: "Payment",
    drive: "Drive",
    portfolio: "Portfolio",
    tools: "Tools",
    automation: "Automation",
    connector: "Connectors",
    settings: "My account",
    account: "Account",
    privacy: "Privacy",
    notifications: "Notifications",
    team: "Team",
    activity: "Activity",
    research: "Discover",
    messages: "Messages",
    profileSection: "Profile section",
    follow: "Follow",
    subscribe: "Subscribe",
    share: "Share",
    editMode: "Edit mode",
    follower: "followers",
    sendMessage: "Send a message",
    professional: "Professional",
    manager: "Manager",
    active: "Active",
    inactive: "Inactive",
    info: "Info",
    home: "Home",
    homeTab: "Home",
    profileWebTab: "Web profile",
    shop: "Shop",
    event: "Event",
    service: "Services",
    news: "News",
    video: "Videos",
    bio: "Bio",
    faq: "F.A.Q",
    parcours: "Journey",
    histoire: "Story",
    // header menu
    headerProfile: "My profile",
    headerSwitchLang: "Français",
    darkMode: "Dark mode",
    lightMode: "Light mode",
    logout: "Log out",
    customLinks: "Links",
    reportAccount: "Report account",
    blockAccount: "Block",
    copyLink: "Copy profile link",
    aboutMe: "About",
    contact: "Contact",
    stats: "Stats",
    yearsActive: "Years active",
    projects: "Projects delivered",
    clients: "Clients",
    location: "Location",
    all: "All",
    package: "Packages",
    haircut: "Cut & style",
    beard: "Beard",
    smoothing: "Smoothing",
    discover: "Discover entrepreneurs",
    discoverSub: "Everything a website can do — centralised in one profile.",
    searchPlaceholder: "Find a stylist, photographer, coach…",
    searchBtn: "Search",
    trending: "Trending",
    nearby: "Near you",
    nothingHere: "Nothing here yet",
    addContent: "Add content from edit mode.",
    thisMonth: "This month",
    lastMonth: "Last month",
    paid: "Collected",
    pending: "Pending",
    addCard: "Add a card",
    defaultCard: "Default",
    expires: "Expires",
    addStep: "Add a step",
    save: "Save",
    cancel: "Cancel",
    close: "Close",
    activate: "Activate",
    deactivate: "Hide",
    drag: "Drag to reorder",
    open: "Open",
    closed: "Closed",
    fileName: "Name",
    fileSize: "Size",
    fileModified: "Modified",
    fileOwner: "Owner",
    upload: "Upload",
    newFolder: "New folder",
    me: "Me",
    you: "You",
    today: "Today",
    yesterday: "Yesterday",
    typeMessage: "Type a message…",
    send: "Send",
  },
};

window.I18N = I18N;
window.useT = function useT(lang) {
  return React.useCallback((k) => (I18N[lang] && I18N[lang][k]) || k, [lang]);
};
